[build]
  base = "/opt/build/repo/oliveto-progetto"
  command = "npm install && npm run build"
  publish = "/opt/build/repo/oliveto-progetto/oliveto-progetto/build"

[build.environment]
  CI = "true"
  REACT_APP_SERVER_BASE_URL = http://localhost:5050
